### ISSUE TITLE
How do I view the graphic rendering when running on OV-Farm on kubernetes

### ISSUE THREAD

**Issue by maprager** [j3soon/omni-farm-isaac#1]
I am starting to get into AI use - and NVIDIA work - but unfortunately, am not very experienced in this area.
I am interested in getting the omni-farm-isaac sim working under on-prem kubernetes. Yesterday, I managed to get the basic sim working on our kubernetes stack using ov-farm installed on k8s. The sim ran - however, we would like to see the ui of the sim - and not just the log output.
From my brief scan of the documentation - I understand, that I would need a streaming client - but I am not sure how this would all fit together. 
I followed the instruction of the ov-farm installation from NVIDIA - and have the following pods on my system:

NAME                                        READY   STATUS    RESTARTS   AGE
controller-d44579b69-h4gg8                  1/1     Running   0          15d
curl                                        1/1     Running   0          16d
mysql-0                                     1/1     Running   1          15d
omniverse-farm-agents-76c859b898-wcznk      1/1     Running   0          15d
omniverse-farm-dashboard-6c9455847c-bwjj9   1/1     Running   0          15d
omniverse-farm-jobs-5f7b8f7567-jzxr8        1/1     Running   0          15d
omniverse-farm-logs-5c4b775967-8nlst        1/1     Running   0          15d
omniverse-farm-metrics-7f775b5d9-ltcgl      1/1     Running   0          15d
omniverse-farm-retries-7dd85f8fc-47vg7      1/1     Running   0          15d
omniverse-farm-settings-d8895c95-gbz2d      1/1     Running   0          15d
omniverse-farm-tasks-5cdd9f69fc-lb9n6       1/1     Running   0          15d
omniverse-farm-ui-85fb45bf89-xgvs8          1/1     Running   0          15d
redis-master-0                              1/1     Running   1          15d

Is there anyway, you can please provide some guidance - on how we could see the ui for the isaac-sim - what pods I need, and how to view the ui ?

**Comment by j3soon** [comment]
Hi,

As mentioned in [the official introduction to Omniverse Farm](https://docs.omniverse.nvidia.com/farm/latest/index.html), it is designed to handle batch jobs for rendering and simulation. This repo contains unofficial scripts to streamline the process of running Isaac Sim/Lab jobs.

For Omniverse Streaming, you may want to refer to the [Omniverse Application Streaming API (OVAS)](https://docs.omniverse.nvidia.com/ovas/latest/index.html).
